### ISSUE TITLE
Wireframe site news

### ISSUE THREAD

**Issue by RenaudPavie** [RenaudPavie/My-news#1]
--------------------------------------------------------------------------------------------------------------------------------------------
MAQUETTE PC :
--------------------------------------------------------------------------------------------------------------------------------------------
![Maquette-pc](https://user-images.githubusercontent.com/24272616/100762763-aa789c80-33f4-11eb-9fc4-5bb85f2092be.png)

--------------------------------------------------------------------------------------------------------------------------------------------
MAQUETTE TABLETTE ( Même que pc, mais avec moins de marge ) :
--------------------------------------------------------------------------------------------------------------------------------------------
![Maquette-tab](https://user-images.githubusercontent.com/24272616/100762777-ac426000-33f4-11eb-919c-abfaa8af04e1.png)

--------------------------------------------------------------------------------------------------------------------------------------------
MAQUETTE MOBILE :
--------------------------------------------------------------------------------------------------------------------------------------------
![Maquette-phone](https://user-images.githubusercontent.com/24272616/100762783-aea4ba00-33f4-11eb-8e53-525fa7da1e3f.png)

Voici les 3 wireframes créé pour la page d'accueil en version pc/tablette et mobile.

Dans l'idée, on arrive sur le site avec une grosse recommandation principale, puis on à accès à tous les articles. 
(La recommandation uniquement dans le bleu clair, en scrollant le site sera majoritairement sur fond sombre )
Ou on peut cliquer dans la barre de navigation pour avoir les articles de la catégorie sélectionnée.

La page de chaque catégorie aura un design très semblable à celle de la page d'accueil, avec la recommandation de la catégorie en haut, puis tous les articles de celle-ci.

Uniquement la page de détail d'article sera distinctement différente.

**Comment by Herondil** [comment]
Ok, dans l'idée le bandeau d'articles mis en avant est très fréquent, peut-être que tu pourrais être plus ambitieux et mettre un slider ?

Aussi, est-ce qu'il n'y aura que 2 articles affichés sur la page ? Tu parles de scroller sur le site.

**Comment by RenaudPavie** [comment]
Oui j'avais pensé a un slider d'article dans l'en-tete pour les recommandations mais c'est une idée noté que j'ai pas mis en page sur le wireframe.

Non il y aura tous les articles d'afficher. Il faudra scroller, auquel cas la partie recommandation ne sera plus visible et le site n'aura plus de background bleu clair.

On pourra ainsi défiler dans tous les articles du site ( à réfléchir si j'impose une limite ) qui suivent.
Même principes pour les pages catégories sauf qu'il n'y aura que des articles de cette catégorie, avec une recommandation adéquate

**Comment by RenaudPavie** [comment]
Et pour re-répondre à la seconde question, je pense que sur la version pc / tablette, l'article d'en-tête sera plus petit, et je pourrais afficher en dessous entre 2 et 3 articles.
(Pas super bonne proportion dans le wireframe au final)

Ce qui ferait 3 ou 4 article d'afficher pour ces versions.

**Comment by Herondil** [comment]
Ok alors dans ce cas je veux bien que tu fasses une nouvelle proposition !

Aussi pour le scroll, il ne faut pas hésiter à rajouter de la hauteur à ton image, on voit parfois des wireframes avec une très grande hauteur parce qu'il y a beaucoup à scroller. Dans ce cas, on met des pointillés pour délimiter la ligne de flottaison.

**Comment by RenaudPavie** [comment]
![Update](https://user-images.githubusercontent.com/24272616/101028639-1b48c180-3579-11eb-96c3-c3ca346aca95.png)

![update-mob](https://user-images.githubusercontent.com/24272616/101033042-5bf50a80-357a-11eb-995e-d2fe71158d7f.png)

Voici un update pour la version desktop et mobile, avec de meilleurs proportions et plus d'articles à l'affichage. 
Ligne de flottaison ajouté sur la version desktop. 
Pour la version mobile, considérons que la hauteur de la maquette est égale à la taille de l'écran.

**Comment by Herondil** [comment]
Ok, pour moi c'est bon !
